import "~/styles/globals.css"

import { Aleo, Montserrat } from "next/font/google"
import { type Metadata } from "next"
import Navbar from "~/ui/Navbar"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const aleo = Aleo({
  subsets: ["latin"],
  variable: "--font-aleo",
})
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${aleo.variable} ${montserrat.variable} text-primary`}
    >
      <body className="bg-cream flex flex-col lg:mx-44 lg:my-16">
        <h1 className="lg:mb-16">Chris Jiang | Portfolio & CV</h1>
        <div className="flex items-start gap-16">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
